services:
  nextjs-workspace-devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/monorepo-root-as-nextjs-workspace:cached
      - vscode-extensions:/root/.vscode-server/extensions
    command: sleep infinity
    environment:
      - WORKSPACE_ROOT=/monorepo-root-as-nextjs-workspace
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1

volumes:
  vscode-extensions:

